apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shop
resources:
  - web.yaml
  - api.yaml
  - payments.yaml
  - recs.yaml
  - worker.yaml
  - receipts.yaml
  - cart-cleanup.yaml
  - servicemonitors.yaml
