apiVersion: apps/v1
kind: Deployment
metadata:
  name: recs
  labels:
    app: recs
    app.kubernetes.io/part-of: shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recs
  template:
    metadata:
      labels:
        app: recs
        app.kubernetes.io/part-of: shop
    spec:
      containers:
        - name: recs
          image: 490233488193.dkr.ecr.us-east-2.amazonaws.com/shop:1.0.2
          args: ["recs"]
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: http
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: recs
  labels:
    app: recs
    app.kubernetes.io/part-of: shop
spec:
  selector:
    app: recs
  ports:
    - name: http
      port: 8080
      targetPort: http
